// <auto-generated />
namespace CRPApp.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class UpdateNullableColumnsIsOnsiteAndLastAccessedDateTime : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UpdateNullableColumnsIsOnsiteAndLastAccessedDateTime));
        
        string IMigrationMetadata.Id
        {
            get { return "201909130335348_UpdateNullableColumnsIsOnsiteAndLastAccessedDateTime"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
